//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2012
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailNation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RailNation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!DOCTYPE tmx SYSTEM &quot;http://www.gala-global.org/oscarStandards/tmx/tmx14.dtd&quot;&gt;
        ///&lt;tmx version=&quot;1.4&quot;&gt;
        ///  &lt;header creationtoolversion=&quot;0.1a&quot; datatype=&quot;plaintext&quot; o-tmf=&quot;csv&quot; creationtool=&quot;loki&quot; srclang=&quot;en-GB&quot; adminlang=&quot;de&quot; segtype=&quot;sentence&quot;/&gt;
        ///  &lt;body&gt;
        ///    &lt;tu tuid=&quot;INTERNAL_LOCALIZATION_VERSION_GAME&quot;&gt;
        ///      &lt;note&gt;ID=INTERNAL_LOCALIZATION_VERSION_GAME : Version of this file, no string for the game&lt;/note&gt;
        ///      &lt;prop type=&quot;x-target&quot;&gt;Server&lt;/prop&gt;
        ///           &lt;tuv xml:lang= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cityNames {
            get {
                return ResourceManager.GetString("cityNames", resourceCulture);
            }
        }
    }
}
